version: '3.7'

services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: anote
      POSTGRES_PASSWORD: anote
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4
    depends_on:
      - database
    restart: always
    ports:
      - 3000:8080

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.0
    depends_on:
      - elasticsearch
    ports:
      - 3001:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kbn-data:/usr/share/kibana/data

  server:
    container_name: server
    build:
      dockerfile: dockerfile
      context: .
    image: anote/server:v1
    ports:
      - '8080:8080'
    depends_on:
      - database

volumes:
  pg-data:
  es-data:
  kbn-data: