# build the server
FROM golang:1.21.1 as build

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

COPY . ./

RUN go mod download

RUN go build -o bin/server cmd/anote/main.go

ENTRYPOINT [ "./bin/server" ]
