name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: |
          docker-compose build

  go-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: |
          cd server
          go mod download
          go mod verify

      - name: Run Go Tests
        run: go test -v ./...

  cypress-test:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
