name: CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: |
          cd backend
          go mod download
          go mod verify

      - name: Run Tests
        run: go test -v ./...

  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies for Frontend
        run: npm ci
        working-directory: client

      - name: Build Frontend
        run: npm run build
        working-directory: client

      - name: Run Cypress Tests in Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          start: npm start
          wait-on: "http://localhost:3000"
          working-directory: client
