name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: |
          docker-compose build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy Docker Containers
        run: |
          docker-compose up -d
          sleep 120

  go-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: |
          cd server
          go mod download
          go mod verify

      - name: Run Go Tests
        run: 
        cd server
        go test -v ./...

  cypress-test:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Check All Container URLs
        run: |
          containers=$(docker ps --format "{{.Names}}")
          for container in $containers; do
            echo "Checking if $container is running:"
            docker inspect -f '{{.State.Status}}' "$container"

            # Get the exposed ports of the container
            ports=$(docker inspect -f '{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} {{end}}' "$container")

            # Loop through each exposed port
            for port in $ports; do
              # Extract the host port from the "HostPort" field
              host_port=$(echo "$port" | awk '{print $3}')

              # Check the URL using the host port
              url="http://localhost:$host_port"
              echo "Checking URL $url for $container:"
              
              # Run curl, but don't stop the script if it fails
              curl --retry 5 --retry-delay 10 --retry-connrefused "$url" || true
            done
          done

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          wait-on: "http://localhost:3000/"
          wait-on-timeout: 300
