name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  cypress-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Containers
        run: |
          docker-compose build

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Docker Containers
        run: |
          docker-compose up -d
          sleep 120

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Docker Container
        run: docker ps

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          wait-on: "http://localhost:3000/"
          wait-on-timeout: 60

  go-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: |
          cd server
          go mod download
          go mod verify

      - name: Run Go Tests
        run: |
          cd server
          go test ./... -cover
